database:
  connection_id: postgres_dev
  
tables:
  CTBank_Temp:
    - name: CTBank_Temp
      sink_table: CTBank_Temp
      database_name:
      primary_key: BankId
      updated_column: UpdateDate
      airflow_asset_name: CTBank_Temp_trigger_asset
      insert_chunk_size: